language: elixir

elixir:
  - '1.7.2'

install:
  - sudo apt-get update
  - bash travis_install.sh
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get

before_script:
 - ./parity --chain dev --unlock=0x00a329c0648769a73afac7f9381e08fb43dbea72 --reseal-min-period 0 --password passfile &

script:
 -  mix test
